version: "4.0"

services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    user: root
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"       # Expose MongoDB port to host (optional but useful)
    volumes:
      - mongo-data:/data/db # Persist MongoDB data between restarts

volumes:
  mongo-data:
